### PR TITLE
dropped the php-coveralls requirement; updated the version of codecli…

### PR DESCRIPTION
**Pull request by elstamey**
…mate 

(addresses #2 )

### CODE REVIEW

**Comment by elstamey** [comment]
this brought in php-coveralls 1.0.0, but I'd like another person for confirm whether this resolves the issue satisfactorily

**Comment by svpernova09** [comment]
1 nitpick change, Since they're slow moving on versioning (0.1, 0.2, 0.3.x, etc) lets not use:
`"codeclimate/php-test-reporter": "~0",` and instead be specific `"codeclimate/php-test-reporter": "~0.3",` _just_ incase they go ham with updates.

**Comment by elstamey** [comment]
I just noticed that technically this doesn't get us away from the abandoned guzzle/guzzle reference.

```
local: phergie-irc-bot-react-development $ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Writing lock file
Generating autoload files
```

**Comment by elstamey** [comment]
@svpernova09 ready for review, but i don't think this closes the issue.

**Comment by svpernova09** [comment]
We needed these changes but you were right, this doesn't solve the Guzzle version problem. We have to wait for `satooshi/php-coveralls` to tag a new release. It's fixed in master, but not in a tagged release.

**Pull request merged**
